appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: yEkJQUq+VKwLzwrZFjXUA8nKZiZD+SiJmrJrDbzuuXklrPhQ9ZeyxmoFr/m9DXEaue3vdTN2Y905cuG5nmr5aMgbv45Ow55DHP49+glrcivAe3MsjlSrG7KVW0ZIunRNGFyjP2HXrrdtlgQiXgdCgUI8/Vorv6c6D/qYJqOOUGERb24EL82CcGMFKAfBZe4HCSwtlgdishIMabmvAqYzlk1o6RF7reO//9BRtAA9pzcbOl5E+lHuEhEJAmaWfbRipW42i7R+beA6x1KuJsv12MOHzzcABV11XWAFgTcWTZ5sUZQ0r2F1oMyveO51RKp0or0c5xR6BtxtM4odPz2Wo/VA7OSLZeUdiKsEuErIMOO1QMHhcroQxfBpRroYI160wh8T+LBg+ycBpeuFXkVptNDvLAZPsMj+qA28Igd4bgJc6w2r1tgonHvfamKCvvD1Z0t2ybv9fsoDg77ZB5B9xg8PzIwjnbygd5uQo5bOtEXccvnvHbZA47DrfK785GqbQ6BfYJAduiFxYL8oeXuIhpZ1xXkcdRrAcg69FJauW8S+4++dd7zee/PkEmQOFj5x6IQygmkIYyodtmJENltm3Z0om8/+z3xo2RGsRyVf/xjvzpcEAX4KlnWl7NmYHA5M8KuZBwB1Y/Ect5mcb46IZBsB6M74LKlt9pqQyl/O4pM=
conda_forge_output_validation: true
